### ISSUE TITLE
Send logs to console output AND default log channel?

### ISSUE THREAD

**Issue by webcraft** [dev-this/laravel-console-logg#6]
Hi! Thank you for this package, this is exactly what I was looking for.

Question though: do I get it correctly that, once this package is installed, the logs from console command won't be sent to their default logging channel anymore? If that's the case, it's a downside for me: I want to be able to look up the output in my daily logs for scheduled commands.

Or maybe something is wrong in my setup? Thanks for clarifying!

**Comment by VeryStrongFingers** [comment]
From memory It's very possible your log channel driver could be overridden, so it's likely not related to your setup.

Let me write a test-case for you and see if I can transform the package into an real driver, which would allow compatibility with the "stack" channel driver.

**Comment by webcraft** [comment]
Oh, didn't think of that option, but that would be a good solution indeed. Would be nice if you could pull that off :+1:

Thanks for the reply!

**Comment by VeryStrongFingers** [comment]
Try out https://github.com/dev-this/laravel-console-logg/releases/tag/v1.2 and take a re-read of https://github.com/dev-this/laravel-console-logg#install
It should be play nice as any other logging channel now

**Comment by webcraft** [comment]
Wow, thanks! Gonna try this out soon :-)
